
const SUPA=window.supabaseClient;
const WA='51944845342';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function waLink(name=''){return `https://wa.me/${WA}?text=${encodeURIComponent('Hola VELORIA, quiero consultar por '+name+'.')}`}
function nav(active){return `<header class="top"><div class="nav site"><a class="brand" href="index.html">VELORIA<small>PERFUMERÍA · ESENCIA QUE DEJA HUELLA</small></a><nav class="menu"><a class="${active==='inicio'?'active':''}" href="index.html">Inicio</a><a class="${active==='catalogo'?'active':''}" href="catalogo.html">Catálogo</a><a class="${active==='dama'?'active':''}" href="dama.html">Damas</a><a class="${active==='caballero'?'active':''}" href="caballero.html">Caballeros</a><a class="${active==='promos'?'active':''}" href="promociones.html">Promociones</a><a class="${active==='contacto'?'active':''}" href="contacto.html">Contacto</a><a class="wa" target="_blank" href="${waLink('una fragancia')}">WhatsApp</a></nav></div></header>`}
async function getProducts(cat){if(!SUPA)return[];let q=SUPA.from('products').select('*').eq('active',true).order('sort_order',{ascending:true}).order('id',{ascending:true});if(cat)q=q.eq('category',cat);const {data}=await q;return data||[]}
function card(p){let img=p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<div class="ph">VELORIA</div>`;let price=Number(p.price||0).toFixed(2);let old=p.old_price?`<span class="old">S/ ${Number(p.old_price).toFixed(2)}</span>`:'';return `<article class="card"><div class="photo">${img}</div><h3>${esc(p.name)}</h3><p class="inspiration">Inspirado en ${esc(p.inspiration||'un aroma icónico')}</p><p class="meta">${esc(p.size_ml||30)} ml</p><p class="price">${old}S/ ${price}</p><a class="order" target="_blank" href="${waLink(p.name)}">Pedir por WhatsApp</a></article>`}
async function renderProducts(cat,id){const el=document.getElementById(id);if(!el)return;const data=await getProducts(cat);el.innerHTML=data.length?data.map(card).join(''):`<p class="sub">Próximamente encontrarás aquí nuestras fragancias.</p>`}
async function renderPromo(){const el=document.getElementById('promo');if(!el||!SUPA)return;const {data}=await SUPA.from('promotions').select('*').eq('active',true).order('id',{ascending:true}).limit(1);const p=data?.[0];if(!p){el.innerHTML='<p class="sub">Próximamente nuevas promociones.</p>';return}el.innerHTML=`<div class="promo"><div><div class="eyebrow">PROMOCIÓN EXCLUSIVA</div><h2>${esc(p.name)}</h2><p>${esc(p.description||'Dos esencias, una conexión.')}</p><div class="promo-price">S/ ${Number(p.price||55).toFixed(2)}</div><a class="btn" target="_blank" href="${waLink(p.name)}">Pedir por WhatsApp →</a></div><div class="hero-art"><div class="bottle b1"><span>30 ML</span></div><div class="bottle b2"><span>30 ML</span></div></div></div>`}
